<a href="https://colab.research.google.com/github/nguyentantan141/MACHINE-LEARNING/blob/Machine-learning/Logistic_SCIPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thư viện

In [ ]:
import numpy as np
import os
from sklearn import preprocessing
from scipy import optimize


In [ ]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive


#Đọc dữ liệu

In [ ]:
def readData(pathfolder: str, filename: str):
  data=np.loadtxt(os.path.join(pathfolder, filename),delimiter=',')
  X, y = data[:,:-1], data[:, -1]
  return X, y

# Tiền xử lý dữ liệu

In [ ]:

def scaling_minmax_norm(data):
  scaler = preprocessing.MinMaxScaler()
  #Phải thực hiện thao tác fit(data) trước khi điều chỉnh dữ liệu
  scaler.fit(data)
  #Thực hiện điều chỉnh dữ liệu
  data = scaler.transform(data)
  return data

In [ ]:
def scaling_center(data):
  scaler = preprocessing.StandardScaler()
  #Phải thực hiện thao tác fit(data) trước khi điều chỉnh dữ liệu
  scaler.fit(data)
  #Thực hiện điều chỉnh dữ liệu
  data = scaler.transform(data)
  return data

In [ ]:
def scaling_X(X,mode:str):
    if mode=='center':
      X_scl = scaling_center(X)
    if mode=='minmax':
      X_scl=scaling_minmax_norm(X)
    m=X.shape[0]
    X_scl=np.hstack((np.ones((m,1)),X_scl))
    return X_scl

# Hồi quy Logistic

In [ ]:
def sigmoid(X,w):
  h=1/(1+np.exp(-np.dot(X,w)))
  return h


In [ ]:
    
def loss(w,X, y):
  m=y.shape[0]
  h=sigmoid(X,w)
  result = (-1 / m) * np.sum(np.dot(y.T, np.log(h)) + np.dot((1 - y).T, np.log(1 - h)))
  return result




In [ ]:
def minimize_scipy(X,y,w,n_iters):
    #Thứ tự xuất hiện các tham số của hàm loss phải đổi lại theo thứ tự trong optimize.minimize là
    #loss(w, X, y)
    #result = optimize.minimize(fun=loss, x0=w, args=(X,y),method='L-BFGS-B',options={"maxiter":n_iters} )
    #result
    #W_optimal của dữ liệu được chuẩn hóa theo center scaling :
    #[1.71844823 3.99278157 3.72513806]
    #W_optimal của dữ liệu được chuẩn hóa theo min-max normalization:
    #[-12.79664873  14.38867203  13.75379772]
    result = optimize.minimize(fun=loss, x0=w, args=(X,y),method='TNC',options={"maxiter":n_iters} )
    #result
    #W_optimal của dữ liệu được chuẩn hóa theo center scaling :
    #[1.718648   3.99314841 3.72535617]
    #W_optimal của dữ liệu được chuẩn hóa theo min-max normalization:
    #[-12.79969199  14.39231687  13.7570447 ]
    w_optimal = result.x
    J_optimal = result.fun
    return w_optimal, J_optimal

In [ ]:
def main(pathfolder: str, filename: str):
  X,y=readData(pathfolder, filename)
  X_scl_center=scaling_X(X,'center')
  X_scl_minmax=scaling_X(X,'minmax')
  w=np.zeros(X_scl_center.shape[1])
  n=1000
  w_his_center,j=minimize_scipy(X_scl_center,y,w,n)
  w_his_minmax,j=minimize_scipy(X_scl_minmax,y,w,n)
  print("W_optimal của dữ liệu được chuẩn hóa theo center scaling :\n",w_his_center)
  print("W_optimal của dữ liệu được chuẩn hóa theo min-max normalization:\n",w_his_minmax)

In [ ]:
if __name__ == "__main__":
  main('/content/drive/MyDrive/Data/data/','ex2data1.txt')

W_optimal của dữ liệu được chuẩn hóa theo center scaling :
 [1.718648   3.99314841 3.72535617]
W_optimal của dữ liệu được chuẩn hóa theo min-max normalization:
 [-12.79969199  14.39231687  13.7570447 ]
