<a href="https://colab.research.google.com/github/nguyentantan141/MACHINE-LEARNING/blob/Machine-learning/Logistic_Sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thư viện

In [1]:
import numpy as np
import os
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression


In [2]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive


#Đọc dữ liệu

In [4]:
def readData(pathfolder: str, filename: str):
  data=np.loadtxt(os.path.join(pathfolder, filename),delimiter=',')
  X, y = data[:,:-1], data[:, -1]
  return X, y

# Tiền xử lý dữ liệu

In [5]:

def scaling_minmax_norm(data):
  scaler = preprocessing.MinMaxScaler()
  #Phải thực hiện thao tác fit(data) trước khi điều chỉnh dữ liệu
  scaler.fit(data)
  #Thực hiện điều chỉnh dữ liệu
  data = scaler.transform(data)
  return data

In [6]:
def scaling_center(data):
  scaler = preprocessing.StandardScaler()
  #Phải thực hiện thao tác fit(data) trước khi điều chỉnh dữ liệu
  scaler.fit(data)
  #Thực hiện điều chỉnh dữ liệu
  data = scaler.transform(data)
  return data

In [7]:
def scaling_X(X,mode:str):
    if mode=='center':
      X_scl = scaling_center(X)
    if mode=='minmax':
      X_scl=scaling_minmax_norm(X)
    m=X.shape[0]
    X_scl=np.hstack((np.ones((m,1)),X_scl))
    return X_scl

# Hồi quy Logistic

In [11]:
def lr(X,y,sol:str):
  #Khởi tạo mô hình
  model = LogisticRegression(solver=sol)
  #Huấn luyện mô hình với tập dữ liệu X, y
  model.fit(X,y)
  #Bộ trọng số tối ưu:
  return  model.coef_

In [31]:
def main(pathfolder: str, filename: str):
  X,y=readData(pathfolder, filename)
  X_scl_center=scaling_X(X,'center')
  X_scl_minmax=scaling_X(X,'minmax')
  w=np.zeros(X_scl_center.shape[1])
  n=1000
  w_his_center=lr(X_scl_center,y,'lbfgs')
  w_his_minmax=lr(X_scl_minmax,y,'sag')
  print("W_optimal của dữ liệu được chuẩn hóa theo center scaling :\n",w_his_center)
  print("W_optimal của dữ liệu được chuẩn hóa theo min-max normalization:\n",w_his_minmax)

In [32]:
if __name__ == "__main__":
  main('/content/drive/MyDrive/Data/data/','ex2data1.txt')

W_optimal của dữ liệu được chuẩn hóa theo center scaling :
 [[-3.89764541e-05  2.28480941e+00  2.09157363e+00]]
W_optimal của dữ liệu được chuẩn hóa theo min-max normalization:
 [[-8.27535666e-05  3.12260129e+00  2.82322812e+00]]


* THUẬT TOÁN TỐI ƯU 'LBFGS'

W_optimal của dữ liệu được chuẩn hóa theo min-max normalization:
 
 [[1.45627316e-08 3.12282175e+00 2.82350117e+00]]

* THUẬT TOÁN TỐI ƯU 'SAGA'

W_optimal của dữ liệu được chuẩn hóa theo min-max normalization:
 
 [[-1.59418694e-03  3.12255276e+00  2.82322465e+00]]
 * THUẬT TOÁN TỐI ƯU 'SAG'

W_optimal của dữ liệu được chuẩn hóa theo min-max normalization:
 
[[-2.23208525e-05  3.12313432e+00  2.82317096e+00]]